<?php

namespace App\Mod\ContentField\Domain;

use Symfony\Component\HttpFoundation\Request;
use App\Domain\BaseService;
use App\Mod\ContentField\Domain\Models\ContentCustomField;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

/**
 * @property ContentCustomField $model
 */
class ContentCustomFieldService extends BaseService
{
    public function __construct(ContentCustomField $model)
    {
        parent::__construct($model);
    }

    public function findList(Request $request, ?int $limit = null, array $with = [], string $flatMethod = 'toFlatArray'): array
    {
        if (!$limit) {
            $limit = config('content_field.list.limit');
        }
        return parent::findList($request, $limit, $with, $flatMethod); // TODO: Change the autogenerated stub
    }

    public function beforeSave(Request $request, ContentCustomField $post, array &$inputs): void
    {
        // fields不要
        unset($inputs['fields']);

        // 参照コンテンツ
        if (!empty($inputs['content_reference_id'])) {
            $post->content_reference_id = $inputs['content_reference_id']['value'];
            unset($inputs['content_reference_id']);
        }
    }

    public function afterSave(Request $request, ContentCustomField $post, mixed $id = null): void
    {
        // fields登録
        $fields = $request->input('fields', []);

        // 既存のフィールドIDを取得
        $existingIds = $post->fields()->pluck('id')->toArray();
        // リクエストから送られてきたフィールドIDを取得
        $incomingIds = collect($fields)->pluck('id')->filter()->toArray();

        // 削除すべきフィールドのIDを特定（既存のIDにあって、リクエストのIDにないもの）
        $idsToDelete = array_diff($existingIds, $incomingIds);

        // 不要になったフィールドを削除
        if (!empty($idsToDelete)) {
            $post->fields()->whereIn('id', $idsToDelete)->delete();
        }

        // 各フィールドをループして、更新または新規作成
        foreach ($fields as $key => $fieldData) {
            $fieldData['model_id'] = $post->model_id;
            $fieldData['is_top_field'] = false;
            $fieldData['sort_num'] = ($key + 1);

            if (!empty($fieldData['content_reference_id'])) {
                $fieldData['content_reference_id'] = $fieldData['content_reference_id']['value'];
            }

            $post->fields()->updateOrCreate(
                // IDがあれば更新、なければ新規作成
                ['id' => $fieldData['id'] && \is_numeric($fieldData['id']) ? $fieldData['id'] : null],
                $fieldData
            );
        }
    }

    protected function validateRequest(Request $request, mixed $post = null): void
    {
        $validator = Validator::make(
            $request->all(),
            [
                "name" => ['required'],
                'model_id' => ['required'],
                'field_id' => [
                    'required',
                    Rule::unique('cms_content_custom_field', 'field_id')
                        ->where('model_id', $request->input('model_id'))
                        ->ignore($post->id ?? null)
                ]
            ],
            [
                'name.required' => '名前は必須項目です。',
                'model_id.required' => 'ModelIDは必須項目です。',
                'field_id.required' => 'フィールドIDは必須項目です。',
                'field_id.unique' => 'このフィールドIDは既に使用されています。'
            ]
        );

        $validator->validate();
    }
}
