<?php

namespace App\Mod\ContentField\Domain;

use App\Domain\BaseService;
use App\Mod\Content\Domain\Models\Content;
use Symfony\Component\HttpFoundation\Request;
use App\Mod\ContentField\Domain\Models\ContentField;
use App\Mod\ContentField\Domain\Models\ContentFieldAttribute;
use Attribute;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

/**
 * @property ContentField $model
 */
class ContentFieldService extends BaseService
{

    public function __construct(ContentField $model)
    {
        parent::__construct($model);
    }

    public function findList(Request $request, ?int $limit = null, array $with = [], string $flatMethod = 'toFlatArray'): array
    {
        if (!$limit) {
            $limit = config('content_field.list.limit');
        }
        return parent::findList($request, $limit, $with, $flatMethod); // TODO: Change the autogenerated stub
    }

    public function findDetail(Request $request, mixed $id, array $with = [], string $flatMethod = 'toFlatArray'): mixed
    {
        return parent::findDetail($request, $id, $with, $flatMethod); // TODO: Change the autogenerated stub
    }

    public function beforeSave(Request $request, ContentField $post, array &$inputs): void
    {
        // custom blockのフィールド
        unset($inputs['children_block']);
        $inputs['is_top_field'] = true;

        if (!empty($inputs['content_reference_id'])) {
            $post->content_reference_id = $inputs['content_reference_id']['value'];
            unset($inputs['content_reference_id']);
        }
    }

    public function afterSave(Request $request, ContentField $post, mixed $id = null): void
    {
        // custom blockの保存
        $fieldType = $request->input('field_type');
        if ($fieldType === 'custom_block') {
            $chidrenBlock = $request->input('children_block', []);

            // 既存のブロックIDを取得
            $existingIds = $post->childrenBlock()->pluck('id')->toArray();
            // リクエストから送られてきたブロックIDを取得
            $incomingIds = collect($chidrenBlock)->pluck('id')->filter()->toArray();

            // 削除すべきブロックのIDを特定（既存のIDにあって、リクエストのIDにないもの）
            $idsToDelete = array_diff($existingIds, $incomingIds);

            // 不要になったブロックを削除
            if (!empty($idsToDelete)) {
                $post->childrenBlock()->whereIn('id', $idsToDelete)->delete();
            }

            // 各ブロックをループして、更新または新規作成
            foreach ($chidrenBlock as $key => $blockData) {
                $blockData['model_id'] = $post->model_id;
                $blockData['parent_block_id'] = $post->id;
                $blockData['is_top_field'] = false;
                if (!empty($blockData['content_reference_id'])) {
                    $blockData['content_reference_id'] = $blockData['content_reference_id']['value'];
                }
                $blockData['sort_num'] = ($key + 1);

                $post->childrenBlock()->updateOrCreate(
                    // IDがあれば更新、なければ新規作成
                    ['id' => $blockData['id'] && \is_numeric($blockData['id']) ? $blockData['id'] : null],
                    $blockData
                );
            }
        }
    }

    public function beforeDelete(Request $request, ContentField $post): void
    {
        // attributeの削除
        if ($post->attribute) {
            $post->attribute->delete();
        }
    }

    protected function validateRequest(Request $request, mixed $post = null): void
    {
        // TODO: field_idのユニークチェック
        $validator = Validator::make(
            $request->all(),
            [
                "name" => ['required'],
                'model_id' => ['required'],
                'field_id' => [
                    'required',
                    Rule::unique('cms_content_field', 'field_id')
                        ->where('model_id', $request->input('model_id'))
                        ->whereNull('parent_block_id')
                        ->where('is_top_field', true)
                        ->ignore($post->id)
                ]
            ],
            [
                'name.required' => '名前は必須項目です。',
                'model_id.required' => 'ModelIDは必須項目です。',
                'field_id.required' => 'フィールドIDは必須項目です。',
                'field_id.unique' => 'このフィールドIDは既に使用されています。'
            ]
        );

        $validator->validate();
    }

    protected function appendCriteria(?array $criteria = [], $query): void
    {
        // 親ブロックのみ
        if (!empty($criteria['is_parent']) && $criteria['is_parent']) {
            $query->whereNull('parent_block_id')
                ->whereNull('custom_field_id');
        }
        unset($criteria['is_parent']);

        parent::appendCriteria($criteria, $query);
    }
}
