<?php

namespace App\Mod\ContentModel\Domain;

use App\Domain\BaseService;
use App\Mod\ContentModel\Domain\Models\ContentModelMarkup;
use Symfony\Component\HttpFoundation\Request;
use Illuminate\Support\Facades\Validator;

/**
 * @property ContentModelMarkup $model
 */
class ContentModelMarkupService extends BaseService
{
    public function __construct(ContentModelMarkup $model)
    {
        parent::__construct($model);
    }

    public function findList(Request $request, ?int $limit = null, array $with = [], string $flatMethod = 'toFlatArray'): array
    {
        if (!$limit) {
            $limit = config('content_model_markup.list.limit');
        }
        return parent::findList($request, $limit, $with, $flatMethod); // TODO: Change the autogenerated stub
    }

    protected function validateRequest(Request $request, mixed $post = null): void
    {
        $validator = Validator::make(
            $request->all(),
            [
                'model_id' => ['required'],
                'markup_type' => ['required'],
                'template_json' => ['required'],
            ],
            [
                'model_id.required' => 'ModelIDは必須項目です。',
                'markup_type.required' => 'タイプは必須項目です。',
                'template_json.required' => 'テンプレートJSONは必須項目です。',
            ]
        );

        $validator->validate();
    }
}
