<?php

namespace App\Mod\ContentModel\Domain;

use App\Domain\BaseService;
use App\Core\User\Domain\PermissionService;
use App\Core\Contract\Domain\FacilityAlias;
use Symfony\Component\HttpFoundation\Request;
use App\Mod\ContentModel\Domain\Models\ContentModel;
use App\Mod\Content\Domain\Models\Content;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

/**
 * @property ContentModel $model
 */
class ContentModelService extends BaseService
{

    public function __construct(ContentModel $model)
    {
        parent::__construct($model);
    }

    public function findList(Request $request, ?int $limit = null, array $with = [], string $flatMethod = 'toFlatArray'): array
    {
        if (!$limit) {
            $limit = config('content_model.list.limit');
        }
        return parent::findList($request, $limit, $with, $flatMethod); // TODO: Change the autogenerated stub
    }

    public function beforeSave(Request $request, ContentModel $post, array &$inputs): void
    {
        if (!$post->id) {
            $inputs['api_header_key'] = bin2hex(random_bytes(32));
        }

        // 企業使用と施設使用のチェックボックスは不要
        unset($inputs['is_cms_use_master']);
        unset($inputs['cms_use_facilities']);
    }

    public function afterSave(Request $request, ContentModel $post, mixed $id = null): void
    {
        // 企業を紐付け
        $isCmsMaster = $request->input('is_cms_use_master', false);
        $post->cms_company()->sync($isCmsMaster ? [$request->input('company_id', null)] : []);

        // 施設を紐付け
        $cmsUseFacilities = $request->input('cms_use_facilities', []) ?? [];
        if ($cmsUseFacilities === '') {
            $cmsUseFacilities = [];
        }
        $post->cms_facilities()->sync(\array_map(function ($item) {
            return $item['value'];
        }, $cmsUseFacilities));
    }

    protected function validateRequest(Request $request, mixed $post = null): void
    {
        $validator = Validator::make(
            $request->all(),
            [
                "title" => ['required'],
                'alias' => [
                    'required',
                    Rule::unique($this->model->getTable(), 'alias')
                        ->where('company_id', $request->input('company_id'))
                        ->ignore($post->id ?? null)
                ],
                'webhook_url' => ['nullable', 'url']
            ],
            [
                'title.required' => 'タイトルは必須項目です。',
                'alias.required' => 'エイリアスは必須項目です。',
                'alias.unique' => 'このエイリアスは既に使用されています。',
                'webhook_url.url' => 'Webhook URLは有効なURLではありません。'
            ]
        );

        $validator->validate();
    }

    public function findAll(Request $request, array $with = [], string $flatMethod = 'toFlatArray'): array
    {
        // 権限に基づいてフィルタリング
        $permissionService = app(PermissionService::class);
        $companyAlias = $request->route('company_alias');
        $company = \App\Core\Contract\Domain\Models\ContractCompany::where('alias', $companyAlias)->first();
        $companyId = $company?->id;

        // 施設IDを取得（facility_aliasがある場合）
        $facilityId = null;
        $facilityAlias = $request->route('facility_alias');
        if ($facilityAlias && $facilityAlias !== FacilityAlias::MASTER) {
            $facility = \App\Core\Contract\Domain\Models\ContractFacility::where('alias', $facilityAlias)->first();
            $facilityId = $facility?->id;
        }

        // 権限に基づいてフィルタリング
        $allowedIds = $permissionService->getAllowedResourceIds('content_model', 'read', $companyId, $facilityId);

        if ($allowedIds !== null && !empty($allowedIds)) {
            // 特定のIDのみアクセス可能な場合
            $criteria = $request->get('criteria', []);
            $criteria['id'] = $allowedIds;
            // クエリパラメータとリクエストパラメータの両方に設定
            $request->query->set('criteria', $criteria);
            $request->request->set('criteria', $criteria);
        } elseif ($allowedIds !== null && empty($allowedIds)) {
            // アクセス可能なIDが空の場合は空の結果を返す
            return [
                'data' => [],
            ];
        }

        return parent::findAll($request, $with, $flatMethod);
    }

    public function findOneBy(Request $request, array $with = [], string $flatMethod = 'toFlatArray'): mixed
    {
        return parent::findOneBy($request, $with, $flatMethod);
    }

    /**
     * 現在の登録数を計算してContentModelに追加
     */
    public function addCurrentContentCount(Request $request, mixed $post): mixed
    {
        if (!$post) {
            return $post;
        }

        try {
            $companyAndFacility = $this->findCompanyAndFacility($request);
            $company = $companyAndFacility['company'];
            $facility = $companyAndFacility['facility'];

            // オブジェクトの場合は配列に変換
            $postArray = is_array($post) ? $post : $post->toArray();

            // モデルIDを取得
            $modelId = $postArray['id'] ?? null;

            if ($modelId) {
                $currentCount = Content::where('model_id', $modelId)
                    ->where('company_id', $company->id)
                    ->where('assignable_type', get_class($facility))
                    ->where('assignable_id', $facility->id)
                    ->count();

                // 配列に追加
                $postArray['current_content_count'] = $currentCount;

                // 元がオブジェクトの場合は、オブジェクトにも追加（JSONシリアライズ時に含まれるように）
                if (!is_array($post)) {
                    $post->current_content_count = $currentCount;
                }

                // 配列を返す（オブジェクトの場合は配列に変換して返す）
                return $postArray;
            }
        } catch (\Exception $e) {
            // エラーが発生した場合は0を設定
            $postArray = is_array($post) ? $post : $post->toArray();
            $postArray['current_content_count'] = 0;

            if (!is_array($post)) {
                $post->current_content_count = 0;
            }

            return $postArray;
        }

        // オブジェクトの場合は配列に変換して返す
        return is_array($post) ? $post : $post->toArray();
    }

    protected function appendCriteria(?array $criteria = [], $query): void
    {
        if (!empty($criteria['ignore_model_id'])) {
            $query->where('id', '!=', $criteria['ignore_model_id']);
        }
        unset($criteria['ignore_model_id']);

        // idが配列の場合はwhereInを使用
        if (isset($criteria['id']) && is_array($criteria['id']) && !empty($criteria['id'])) {
            $ids = $criteria['id'];
            unset($criteria['id']);
            $query->whereIn('id', $ids);
        }

        parent::appendCriteria($criteria, $query);
    }
}
