<?php

namespace App\Core\User\Domain;

use App\Domain\BaseService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Core\User\Domain\Models\User;
use App\Core\User\Domain\Models\UserFacilityStaffPermissions;
use App\Core\User\Domain\UserType;
use App\Core\Contract\Domain\Models\ContractCompany;
use App\Core\Contract\Domain\Models\ContractFacility;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Password;
use Illuminate\Support\Str;

/**
 * @property User $model
 */
class UserService extends BaseService
{

    public function __construct(User $model)
    {
        parent::__construct($model);
    }

    public function findList(\Symfony\Component\HttpFoundation\Request $request, ?int $limit = null, array $with = [], string $flatMethod = 'toFlatArray'): array
    {
        if (!$limit) {
            $limit = config('user.list.limit');
        }
        return parent::findList($request, $limit, $with, $flatMethod); // TODO: Change the autogenerated stub
    }

    public function appendCriteria(?array $criteria = [], $query): void
    {
        parent::appendCriteria($criteria, $query); // TODO: Change the autogenerated stub
    }

    public function validateRequest(\Symfony\Component\HttpFoundation\Request $request, mixed $post = null): void
    {
        $rules = [
            "name" => ['required', 'string', 'max:255'],
            "email" => ['required', 'email', 'max:255', 'unique:users,email,' . $post->id],
        ];

        $messages = [
            'name.required' => '名前は必須項目です。',
            'name.string' => '名前は文字列でなければなりません。',
            'name.max' => '名前は255文字以内でなければなりません。',
            'email.required' => 'メールアドレスは必須項目です。',
            'email.email' => 'メールアドレスが不正です。',
            'email.max' => 'メールアドレスは255文字以内でなければなりません。',
            'email.unique' => 'このメールアドレスは既に使用されています。',
        ];

        if (!$post->id || $request->request->get('is_chg_pass') === true) {
            $rules['password'] = ['required', 'string', 'min:8'];
            $messages['password.required'] = 'パスワードは必須項目です。';
            $messages['password.string'] = 'パスワードは文字列でなければなりません。';
            $messages['password.min'] = 'パスワードは8文字以上でなければなりません。';
        }

        $userType = $request->request->get('user_type');
        if ($userType === UserType::COMPANY || $userType === UserType::MANAGE || $userType === UserType::FACILITY) {
            $rules['company_id'] = ['required'];
            $messages['company_id.required'] = '企業は必須項目です。';
        }

        if ($userType === UserType::FACILITY) {
            $rules['facility_id'] = ['required', 'array'];
            $messages['facility_id.required'] = '施設は必須項目です。';
        }


        // 必要に応じてコメントアウト外し、バリデーションを追加する
        $validator = Validator::make(
            $request->request->all(),
            $rules,
            $messages
        );

        $validator->validate();
    }

    public function beforeSave(\Symfony\Component\HttpFoundation\Request $request, mixed $post = null, array &$inputs = []): void
    {
        if (!empty($inputs['password']) && (!$post->id || $inputs['is_chg_pass'])) {
            $post->password = Hash::make($inputs['password']);
            unset($inputs['password']);
        }
        unset($inputs['is_chg_pass']);

        // 企業と施設の紐づけを解除
        unset($inputs['company_id']);
        unset($inputs['facility_id']);

        // 権限設定はafterSaveで処理するため、inputsから除外
        unset($inputs['permission_settings']);

        // is_masterの場合はtwo_factor_enabledをfalseに設定
        if (isset($inputs['is_master']) && $inputs['is_master']) {
            $inputs['two_factor_enabled'] = false;
        } elseif (isset($inputs['user_type']) && $inputs['user_type'] === UserType::MASTER) {
            $inputs['two_factor_enabled'] = false;
        }
    }

    public function afterSave(Request $request, User $post, mixed $id = null): void
    {
        $userType = $request->request->get('user_type', null);

        // 企業を紐づけ
        if ($userType === UserType::COMPANY || $userType === UserType::MANAGE || $userType === UserType::FACILITY) {
            $post->companies()->sync($request->input('company_id', [])['value'] ?? []);
        }


        // 施設を紐づけ
        if ($userType === UserType::FACILITY) {
            $post->facilities()->sync(\array_map(function ($item) {
                return $item['value'];
            }, $request->input('facility_id', [])));
        }

        // 権限設定を保存（企業スタッフまたは施設スタッフの場合のみ）
        if ($userType === UserType::COMPANY || $userType === UserType::FACILITY) {
            $this->savePermissions($request, $post, $userType);
        }
    }

    /**
     * ユーザーの権限設定を取得
     */
    public function getUserPermissions(int $userId): array
    {
        $permissions = UserFacilityStaffPermissions::withoutGlobalScopes()
            ->where('user_id', $userId)
            ->get();

        $result = [];
        foreach ($permissions as $permission) {
            $key = $permission->resource_type . '_' . ($permission->resource_id ?? 'null');

            // 同じリソースタイプとリソースIDの組み合わせが既にある場合はスキップ
            // （施設スタッフの場合、同じリソースに対して複数の施設の権限がある可能性があるため、最初のものを使用）
            if (isset($result[$key])) {
                continue;
            }

            $result[$key] = [
                'resource_type' => $permission->resource_type,
                'resource_id' => $permission->resource_id,
                'read' => [
                    'enabled' => $permission->permission_read,
                    'scope' => $permission->permission_read_scope,
                ],
                'write' => [
                    'enabled' => $permission->permission_write,
                    'scope' => $permission->permission_write_scope,
                ],
                'delete' => [
                    'enabled' => $permission->permission_delete,
                    'scope' => $permission->permission_delete_scope,
                ],
                'sort' => [
                    'enabled' => $permission->permission_sort ?? false,
                ],
            ];
        }

        return array_values($result);
    }

    /**
     * 権限設定を保存
     */
    private function savePermissions(Request $request, User $user, string $userType): void
    {
        $permissions = $request->input('permission_settings', []);

        if (empty($permissions)) {
            // 権限設定が空の場合は、既存の権限を削除
            UserFacilityStaffPermissions::withoutGlobalScopes()
                ->where('user_id', $user->id)
                ->delete();
            return;
        }

        // 企業IDと施設IDを取得
        $companyId = null;
        $facilityIds = [];

        if ($userType === UserType::COMPANY) {
            // 企業スタッフの場合
            $companyId = $request->input('company_id', [])['value'] ?? null;
            if (!$companyId) {
                return; // 企業IDが無い場合は処理しない
            }
        } elseif ($userType === UserType::FACILITY) {
            // 施設スタッフの場合
            $facilityInput = $request->input('facility_id', []);
            $facilityIds = is_array($facilityInput)
                ? array_map(function ($item) {
                    return is_array($item) ? ($item['value'] ?? null) : $item;
                }, $facilityInput)
                : [];

            if (empty($facilityIds)) {
                return; // 施設IDが無い場合は処理しない
            }
        }

        // 既存の権限を削除
        if ($userType === UserType::COMPANY) {
            UserFacilityStaffPermissions::withoutGlobalScopes()
                ->where('user_id', $user->id)
                ->where('company_id', $companyId)
                ->delete();
        } elseif ($userType === UserType::FACILITY) {
            UserFacilityStaffPermissions::withoutGlobalScopes()
                ->where('user_id', $user->id)
                ->whereIn('facility_id', $facilityIds)
                ->delete();
        }

        // 新しい権限を保存
        foreach ($permissions as $permission) {
            $resourceType = $permission['resource_type'] ?? null;
            $resourceId = $permission['resource_id'] ?? null;

            if (!$resourceType) {
                continue;
            }

            // 企業スタッフの場合
            if ($userType === UserType::COMPANY && $companyId) {
                UserFacilityStaffPermissions::create([
                    'resource_type' => $resourceType,
                    'resource_id' => $resourceId,
                    'user_id' => $user->id,
                    'company_id' => $companyId,
                    'facility_id' => null,
                    'permission_read' => $permission['read']['enabled'] ?? false,
                    'permission_read_scope' => $permission['read']['scope'] ?? 'all',
                    'permission_write' => $permission['write']['enabled'] ?? false,
                    'permission_write_scope' => $permission['write']['scope'] ?? 'all',
                    'permission_delete' => $permission['delete']['enabled'] ?? false,
                    'permission_delete_scope' => $permission['delete']['scope'] ?? 'all',
                    'permission_sort' => $permission['sort']['enabled'] ?? false,
                ]);
            }
            // 施設スタッフの場合（各施設ごとに権限を保存）
            elseif ($userType === UserType::FACILITY && !empty($facilityIds)) {
                foreach ($facilityIds as $facilityId) {
                    UserFacilityStaffPermissions::create([
                        'resource_type' => $resourceType,
                        'resource_id' => $resourceId,
                        'user_id' => $user->id,
                        'company_id' => null,
                        'facility_id' => $facilityId,
                        'permission_read' => $permission['read']['enabled'] ?? false,
                        'permission_read_scope' => $permission['read']['scope'] ?? 'all',
                        'permission_write' => $permission['write']['enabled'] ?? false,
                        'permission_write_scope' => $permission['write']['scope'] ?? 'all',
                        'permission_delete' => $permission['delete']['enabled'] ?? false,
                        'permission_delete_scope' => $permission['delete']['scope'] ?? 'all',
                        'permission_sort' => $permission['sort']['enabled'] ?? false,
                    ]);
                }
            }
        }
    }

    public function login(Request $request): array
    {
        $validator = Validator::make($request->all(), [
            'email' => ['required', 'email'],
            'password' => ['required'],
        ], [
            'email.required' => 'メールアドレスは必須項目です。',
            'email.email' => 'メールアドレスが不正です。',
            'password.required' => 'パスワードは必須項目です。',
        ]);

        $validator->validate();

        $email = $request->input('email');
        $ipAddress = $request->ip();

        // ログイン試行回数の設定を取得（整数にキャスト）
        $maxAttempts = (int) config('user.login.max_attempts', 5);
        $lockoutDuration = (int) config('user.login.lockout_duration', 15);

        // キャッシュキー（メールアドレスとIPアドレスの組み合わせ）
        $cacheKey = 'login_attempts:' . md5($email . '|' . $ipAddress);

        // ログイン試行回数を取得
        $attempts = Cache::get($cacheKey, 0);

        // ロックアウトチェック
        if ($attempts >= $maxAttempts) {
            $lockoutKey = 'login_lockout:' . md5($email . '|' . $ipAddress);
            $lockoutUntil = Cache::get($lockoutKey);

            if ($lockoutUntil && now()->lt($lockoutUntil)) {
                $remainingSeconds = now()->diffInSeconds($lockoutUntil);
                $remainingMinutes = floor($remainingSeconds / 60);
                $remainingSecs = $remainingSeconds % 60;
                $timeMessage = $remainingMinutes > 0
                    ? ($remainingSecs > 0 ? "{$remainingMinutes}分{$remainingSecs}秒後" : "{$remainingMinutes}分後")
                    : "{$remainingSecs}秒後";
                throw new \Exception("ログイン試行回数が上限に達しました。{$timeMessage}に再度お試しください。");
            } else {
                // ロックアウト期間が過ぎた場合は、試行回数をリセット
                Cache::forget($cacheKey);
                Cache::forget($lockoutKey);
                $attempts = 0;
            }
        }

        // ステータスがOFFのユーザーはログインできないようにする
        $user = User::where('email', $email)->first();
        if ($user && $user->status === false) {
            // ステータスOFFでも試行回数はカウントしない
            throw new \Exception('このアカウントは無効化されています。');
        }

        if (!Auth::attempt($request->only('email', 'password'))) {
            // ログイン失敗時：試行回数を増やす
            $attempts++;
            Cache::put($cacheKey, $attempts, now()->addMinutes($lockoutDuration));

            // 上限に達した場合はロックアウトを設定
            if ($attempts >= $maxAttempts) {
                $lockoutKey = 'login_lockout:' . md5($email . '|' . $ipAddress);
                Cache::put(
                    $lockoutKey,
                    now()->addMinutes($lockoutDuration),
                    now()->addMinutes($lockoutDuration)
                );
                throw new \Exception("ログイン情報が間違っています。{$maxAttempts}回失敗したため、{$lockoutDuration}分間ログインがロックされました。");
            }

            $remainingAttempts = $maxAttempts - $attempts;
            throw new \Exception("ログイン情報が間違っています。残り試行回数: {$remainingAttempts}回");
        }

        // ログイン成功時：試行回数をリセット
        Cache::forget($cacheKey);
        Cache::forget('login_lockout:' . md5($email . '|' . $ipAddress));

        // SPAクッキー方式: セッションを再生成し、Cookieベースで認証する
        $request->session()->regenerate();

        /** @var User $user */
        $user = Auth::user();

        // is_master以外で、two_factor_enabledがtrueのユーザーは2段階認証をチェック
        if (!$user->is_master && $user->two_factor_enabled !== false) {
            // 最後に2段階認証を通過した日時をチェック
            $lastVerifiedKey = 'two_factor_verified:' . $user->id;
            $lastVerified = Cache::get($lastVerifiedKey);

            // 今日既に認証済みかチェック（日付が変わっていないか）
            $needsTwoFactor = true;
            if ($lastVerified) {
                $lastVerifiedDate = \Carbon\Carbon::parse($lastVerified);
                $needsTwoFactor = !$lastVerifiedDate->isToday();
            }

            if ($needsTwoFactor) {
                // セッションを無効化（認証コード検証後に再ログイン）
                Auth::logout();
                $request->session()->invalidate();
                $request->session()->regenerateToken();

                // 認証コードを生成してメール送信
                $this->generateVerificationCode($user);

                return [
                    'requires_two_factor' => true,
                    'message' => '認証コードをメールで送信しました。コードを入力してください。',
                ];
            }
        }

        // ユーザーが紐づいている企業や施設のステータスをチェック
        if ($user->user_type === UserType::MANAGE || $user->user_type === UserType::COMPANY) {
            // 企業管理者または企業スタッフの場合、紐づいている企業のステータスをチェック
            $companies = $user->companies()->get();
            foreach ($companies as $company) {
                if ($company->status === false) {
                    Auth::logout();
                    $request->session()->invalidate();
                    $request->session()->regenerateToken();
                    throw new \Exception('このアカウントに紐づいている企業が無効化されています。');
                }
            }
        } elseif ($user->user_type === UserType::FACILITY) {
            // 施設スタッフの場合、紐づいている施設とその企業のステータスをチェック
            $facilities = $user->facilities()->with('company')->get();
            foreach ($facilities as $facility) {
                if ($facility->status === false) {
                    Auth::logout();
                    $request->session()->invalidate();
                    $request->session()->regenerateToken();
                    throw new \Exception('このアカウントに紐づいている施設が無効化されています。');
                }
                if ($facility->company && $facility->company->status === false) {
                    Auth::logout();
                    $request->session()->invalidate();
                    $request->session()->regenerateToken();
                    throw new \Exception('このアカウントに紐づいている企業が無効化されています。');
                }
            }
        }
        return [
            'user' => $user->toArray(),
            'message' => 'ログイン成功',
        ];
    }

    public function logout(Request $request): array
    {
        // SPAクッキー方式: セッションを完全に破棄
        Auth::guard('web')->logout();
        $request->session()->flush(); // セッションデータを完全にクリア
        $request->session()->invalidate(); // セッションIDを無効化
        $request->session()->regenerateToken(); // CSRFトークンを再生成
        return [
            'message' => 'ログアウト成功',
        ];
    }

    public function sendResetLink(Request $request): array
    {
        $validator = Validator::make($request->all(), [
            'email' => ['required', 'email'],
        ], [
            'email.required' => 'メールアドレスは必須項目です。',
            'email.email' => 'メールアドレスが不正です。',
        ]);
        $validator->validate();

        $status = Password::broker('users')->sendResetLink(
            $request->only('email')
        );

        if ($status !== Password::RESET_LINK_SENT) {
            throw new \Exception(__($status));
        }

        return [
            'message' => 'パスワードリセット用メールを送信しました。',
            'status' => $status,
        ];
    }

    public function resetPassword(Request $request): array
    {
        $validator = Validator::make($request->all(), [
            'token' => ['required', 'string'],
            'email' => ['required', 'email'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ], [
            'token.required' => 'トークンが無効です。',
            'email.required' => 'メールアドレスは必須項目です。',
            'email.email' => 'メールアドレスが不正です。',
            'password.required' => 'パスワードは必須項目です。',
            'password.min' => 'パスワードは8文字以上でなければなりません。',
            'password.confirmed' => 'パスワード確認が一致しません。',
        ]);
        $validator->validate();

        $status = Password::broker('users')->reset(
            $request->only('email', 'password', 'password_confirmation', 'token'),
            function (User $user, string $password) {
                $user->password = Hash::make($password);
                $user->setRememberToken(Str::random(60));
                $user->save();
            }
        );

        if ($status !== Password::PASSWORD_RESET) {
            throw new \Exception(__($status));
        }

        return [
            'message' => 'パスワードを更新しました。',
            'status' => $status,
        ];
    }

    public function updateMe(Request $request): array
    {
        /** @var User $user */
        $user = Auth::user();

        $validator = Validator::make($request->all(), [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'email', 'max:255', 'unique:users,email,' . $user->id],
            'password' => ['nullable', 'string', 'min:8', 'confirmed'],
        ], [
            'name.required' => '名前は必須項目です。',
            'name.string' => '名前は文字列でなければなりません。',
            'name.max' => '名前は255文字以内でなければなりません。',
            'email.required' => 'メールアドレスは必須項目です。',
            'email.email' => 'メールアドレスが不正です。',
            'email.max' => 'メールアドレスは255文字以内でなければなりません。',
            'email.unique' => 'このメールアドレスは既に使用されています。',
            'password.min' => 'パスワードは8文字以上でなければなりません。',
            'password.confirmed' => 'パスワード確認が一致しません。',
        ]);
        $validator->validate();

        $user->name = $request->input('name');
        $user->email = $request->input('email');
        if ($request->filled('password')) {
            $user->password = Hash::make($request->input('password'));
        }
        $user->save();

        return [
            'user' => $user->toArray(),
            'message' => 'アカウント情報を更新しました。',
        ];
    }

    /**
     * 2段階認証コードを生成してメール送信
     */
    private function generateVerificationCode(User $user): string
    {
        // 6桁のランダムな認証コードを生成
        $code = str_pad((string) random_int(0, 999999), 6, '0', STR_PAD_LEFT);

        // 30分間有効なキャッシュに保存
        $codeKey = 'two_factor_code:' . $user->id;
        Cache::put($codeKey, $code, now()->addMinutes(30));

        // メール送信
        $this->sendVerificationCodeEmail($user, $code);

        return $code;
    }

    /**
     * 認証コード検証メールを送信
     */
    private function sendVerificationCodeEmail(User $user, string $code): void
    {
        Mail::send('emails.two_factor_code', [
            'code' => $code,
            'userName' => $user->name,
        ], function ($message) use ($user) {
            $message->to($user->email)
                ->subject('【abi-CMS】ログイン認証コード');
        });
    }

    /**
     * 2段階認証コードを検証
     */
    public function verifyTwoFactorCode(Request $request): array
    {
        $validator = Validator::make($request->all(), [
            'email' => ['required', 'email'],
            'password' => ['required'],
            'code' => ['required', 'string', 'size:6'],
        ], [
            'email.required' => 'メールアドレスは必須項目です。',
            'email.email' => 'メールアドレスが不正です。',
            'password.required' => 'パスワードは必須項目です。',
            'code.required' => '認証コードは必須項目です。',
            'code.size' => '認証コードは6桁である必要があります。',
        ]);

        $validator->validate();

        $email = $request->input('email');
        $password = $request->input('password');
        $code = $request->input('code');

        $user = User::where('email', $email)->first();
        if (!$user) {
            throw new \Exception('ユーザーが見つかりません。');
        }

        if ($user->is_master) {
            throw new \Exception('マスターユーザーは2段階認証の対象外です。');
        }

        if ($user->two_factor_enabled === false) {
            throw new \Exception('このユーザーの2段階認証は無効化されています。');
        }

        // 認証コードを取得
        $codeKey = 'two_factor_code:' . $user->id;
        $storedCode = Cache::get($codeKey);

        if (!$storedCode || $storedCode !== $code) {
            throw new \Exception('認証コードが正しくないか、有効期限が切れています。');
        }

        // 認証コードを削除
        Cache::forget($codeKey);

        // パスワードで再ログイン
        if (!Auth::attempt(['email' => $email, 'password' => $password])) {
            throw new \Exception('ログインに失敗しました。');
        }

        // セッションを再生成
        $request->session()->regenerate();

        // 今日の認証完了を記録
        $lastVerifiedKey = 'two_factor_verified:' . $user->id;
        Cache::put($lastVerifiedKey, now()->toDateTimeString(), now()->addDay());

        /** @var User $authenticatedUser */
        $authenticatedUser = Auth::user();

        // ユーザーが紐づいている企業や施設のステータスをチェック
        if ($authenticatedUser->user_type === UserType::MANAGE || $authenticatedUser->user_type === UserType::COMPANY) {
            $companies = $authenticatedUser->companies()->get();
            foreach ($companies as $company) {
                if ($company->status === false) {
                    Auth::logout();
                    $request->session()->invalidate();
                    $request->session()->regenerateToken();
                    throw new \Exception('このアカウントに紐づいている企業が無効化されています。');
                }
            }
        } elseif ($authenticatedUser->user_type === UserType::FACILITY) {
            $facilities = $authenticatedUser->facilities()->with('company')->get();
            foreach ($facilities as $facility) {
                if ($facility->status === false) {
                    Auth::logout();
                    $request->session()->invalidate();
                    $request->session()->regenerateToken();
                    throw new \Exception('このアカウントに紐づいている施設が無効化されています。');
                }
                if ($facility->company && $facility->company->status === false) {
                    Auth::logout();
                    $request->session()->invalidate();
                    $request->session()->regenerateToken();
                    throw new \Exception('このアカウントに紐づいている企業が無効化されています。');
                }
            }
        }

        return [
            'user' => $authenticatedUser->toArray(),
            'message' => 'ログイン成功',
        ];
    }

    /**
     * 2段階認証コードを再送信
     */
    public function resendVerificationCode(Request $request): array
    {
        $validator = Validator::make($request->all(), [
            'email' => ['required', 'email'],
        ], [
            'email.required' => 'メールアドレスは必須項目です。',
            'email.email' => 'メールアドレスが不正です。',
        ]);

        $validator->validate();

        $email = $request->input('email');

        $user = User::where('email', $email)->first();
        if (!$user) {
            throw new \Exception('ユーザーが見つかりません。');
        }

        if ($user->is_master) {
            throw new \Exception('マスターユーザーは2段階認証の対象外です。');
        }

        if ($user->two_factor_enabled === false) {
            throw new \Exception('このユーザーの2段階認証は無効化されています。');
        }

        // 再送信制限チェック（60秒以内の再送信を防ぐ）
        $resendKey = 'two_factor_resend:' . $user->id;
        $lastResend = Cache::get($resendKey);

        if ($lastResend && now()->diffInSeconds($lastResend) < 60) {
            $remainingSeconds = 60 - now()->diffInSeconds($lastResend);
            throw new \Exception("認証コードの再送信は{$remainingSeconds}秒後に可能です。");
        }

        // 認証コードを生成してメール送信
        $this->generateVerificationCode($user);

        // 再送信時刻を記録
        Cache::put($resendKey, now(), now()->addMinutes(1));

        return [
            'message' => '認証コードを再送信しました。',
        ];
    }

    /**
     * 2段階認証の有効/無効を設定
     */
    public function setTwoFactorEnabled(Request $request, int $userId): array
    {
        $validator = Validator::make($request->all(), [
            'enabled' => ['required', 'boolean'],
        ], [
            'enabled.required' => '有効/無効の設定は必須です。',
            'enabled.boolean' => '有効/無効の設定は真偽値である必要があります。',
        ]);

        $validator->validate();

        $user = User::findOrFail($userId);

        if ($user->is_master) {
            throw new \Exception('マスターユーザーの2段階認証設定は変更できません。');
        }

        $enabled = $request->input('enabled');
        $user->two_factor_enabled = $enabled;
        $user->save();

        // 無効化する場合、認証済み状態と認証コードをクリア
        if (!$enabled) {
            Cache::forget('two_factor_verified:' . $user->id);
            Cache::forget('two_factor_code:' . $user->id);
            Cache::forget('two_factor_resend:' . $user->id);
        }

        return [
            'user' => $user->toArray(),
            'message' => $enabled ? '2段階認証を有効化しました。' : '2段階認証を無効化しました。',
        ];
    }

    /**
     * 2段階認証の状態をリセット（認証済み状態をクリア）
     */
    public function resetTwoFactor(Request $request, int $userId): array
    {
        $user = User::findOrFail($userId);

        if ($user->is_master) {
            throw new \Exception('マスターユーザーの2段階認証はリセットできません。');
        }

        // 認証済み状態と認証コードをクリア
        Cache::forget('two_factor_verified:' . $user->id);
        Cache::forget('two_factor_code:' . $user->id);
        Cache::forget('two_factor_resend:' . $user->id);

        return [
            'message' => '2段階認証の状態をリセットしました。次回ログイン時に認証コードが要求されます。',
        ];
    }
}
