<?php
namespace App\Mod\ActionLog\Domain;

use App\Domain\BaseService;
use Symfony\Component\HttpFoundation\Request;
use App\Mod\ActionLog\Domain\Models\ActionLog;

/**
 * @property ActionLog $model
 */
class ActionLogService extends BaseService
{

    public function __construct(ActionLog $model)
    {
        parent::__construct($model);
    }

    public function findList(Request $request, ?int $limit = null, array $with = [], string $flatMethod = 'toFlatArray'): array
    {
        if (!$limit) {
            $limit = config('action_log.list.limit');
        }
        return parent::findList($request, $limit, $with, $flatMethod); // TODO: Change the autogenerated stub
    }

    public function appendCriteria(?array $criteria = [], $query): void
    {
        // 実行日時
        if (!empty($criteria['created_at_start'])) {
            $query->where('created_at', '>=', $criteria['created_at_start'] . ' 00:00:00');
        }
        unset($criteria['created_at_start']);

        if (!empty($criteria['created_at_end'])) {
            $query->where('created_at', '<=', $criteria['created_at_end'] . ' 23:59:59');
        }
        unset($criteria['created_at_end']);

        parent::appendCriteria($criteria, $query); // TODO: Change the autogenerated stub
    }
}
