<?php

namespace App\Mod\Content\Domain;

use Symfony\Component\HttpFoundation\Request;
use App\Mod\Content\Domain\Models\Content;
use App\Mod\Content\Domain\Models\ContentValue;
use App\Mod\ContentField\Domain\Models\ContentField;
use App\Mod\ContentModel\Domain\Models\ContentModel;
use App\Services\Validation\FieldValidationService;
use App\Core\User\Domain\PermissionService;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\ValidationException;

/**
 * @property Content $model
 * @property ContentModel $contentModel
 * @property FieldValidationService $validate
 */
class ContentService extends AbstractService
{
    protected $validate;

    public function __construct(Content $model, FieldValidationService $validate)
    {
        parent::__construct($model);
        $this->validate = $validate;
        $this->setContentModel();
    }

    public function findList(Request $request, ?int $limit = null, array $with = [], string $flatMethod = 'toFlatArray'): array
    {
        if (!$limit) {
            $limit = config('content.list.limit');
        }
        return parent::findList($request, $limit, $with, $flatMethod); // TODO: Change the autogenerated stub
    }

    public function findArticle(Request $request, int $contentId): array
    {
        $articleData = [];

        // フィールドの取得
        $fields = $this->contentModel->fields ?? [];
        foreach ($fields as $field) {
            $articleData = \array_merge($articleData, $this->formatArticleSection($field, $contentId));
        }

        // カテゴリの取得
        $categories = $this->model->categories()->getRelated();
        if ($categories) {
            $articleData['categories'] = $categories->toArray();
        }

        return $articleData;
    }

    /**
     * セクションごとの記事データを整形する
     */
    protected function formatArticleSection(ContentField $field, int $contentId, ?int $customFieldId = null, array $formatData = []): array
    {
        switch ($field->field_type) {
            case 'custom_field':
                // カスタムフィールド
                $customFields = $field->customField->fields;
                $customFieldData = [];
                foreach ($customFields as $customField) {
                    $customFieldData = $this->formatArticleSection($customField, $contentId, $customField->id, $customFieldData);
                }
                $formatData[$field->field_id] = $customFieldData;
                break;
            case 'custom_block':
                // カスタムブロック
                $childrenBlock = $field->childrenBlock;
                $customBlockData = [];
                foreach ($childrenBlock as $block) {
                    $customBlockData = $this->formatArticleSection($block, $contentId, null, $customBlockData);
                }
                $formatData[$field->field_id] = $customBlockData;
                break;
            default:
                $value = $field->valueForContent($contentId, $customFieldId);
                if ($value) {
                    $formatData[$field->field_id] = [
                        'id' => $value->id,
                        'value' => $value->value,
                        'custom_content_field_id' => $value->custom_content_field_id
                    ];
                }

                break;
        }

        return $formatData;
    }

    protected function beforeSave($request, $post, &$inputs): void
    {
        // Content Valueに保存するため、fieldの入力値は破棄
        foreach ($this->contentModel->fields as $key => $field) {
            unset($inputs[$field['field_id']]);
        }

        // categoriesも一旦破棄
        unset($inputs['categories']);

        // 検索フィールドをセット
        $post->free_search = serialize($request->all());

        // sort_num追加
        if (!$post->id) {
            $post->sort_num = 0;
        }

        // 紐づけ先をセット
        $companyAndFacility = $this->findCompanyAndFacility($request);
        $company = $companyAndFacility['company'];
        $facility = $companyAndFacility['facility'];

        $post->company_id = $company->id;
        $post->assignable_type = get_class($facility);
        $post->assignable_id = $facility->id;

        // 新規作成時のみ、登録数制限をチェック
        if (!$post->id && $this->contentModel->max_content_count !== null) {
            $currentCount = Content::where('model_id', $this->contentModel->id)
                ->where('company_id', $company->id)
                ->where('assignable_type', get_class($facility))
                ->where('assignable_id', $facility->id)
                ->count();

            if ($currentCount >= $this->contentModel->max_content_count) {
                throw ValidationException::withMessages([
                    'content' => "このコンテンツモデルの登録数が上限（{$this->contentModel->max_content_count}件）に達しています。"
                ]);
            }
        }

        // 更新時のみスコープチェック
        if ($post->id) {
            $this->checkPermissionScope($request, $post, 'write');
        }

        parent::beforeSave($request, $post, $inputs);
    }

    protected function afterSave($request, Content $post, mixed $id = null): void
    {
        // Content Valueの保存
        $inputValues = $request->all();
        $this->saveFieldValues($post, $this->contentModel->fields, $inputValues);

        // カテゴリの保存処理
        $this->saveCategories($post, $request->input('categories', null), $request);

        // WebHook送信
        $this->sendWebhook($post, $post->wasRecentlyCreated ? 'created' : 'updated');
    }

    protected function saveFieldValues(Content $post, Collection $fields, ?array $inputValues, ?array $addValues = []): void
    {
        /** @param ContentField $field */
        foreach ($fields as $field) {
            $fieldId = $field->field_id;
            $fieldType = $field->field_type;

            if (!isset($inputValues[$fieldId])) {
                continue;
            }

            $inputVal = $inputValues[$fieldId];

            switch ($fieldType) {
                case 'custom_block':
                    if (!\is_array($inputVal)) {
                        continue;
                    }

                    // カスタムブロック
                    $usedBlockIds = [];
                    foreach ($inputVal as $key => $value) {
                        $blockSeqId = $value['block_seq_id'];
                        $usedBlockIds[] = $blockSeqId;
                        $this->saveFieldValues(
                            $post,
                            ContentField::where('id', $value['field_id'])->get(),
                            $value['values'],
                            [
                                'block_id' => $field->id,
                                'block_seq_id' => $blockSeqId,
                                'sort_num' => $key + 1
                            ]
                        );
                    }

                    // 使用してないブロックの削除
                    ContentValue::where('block_id', $field->id)->whereNotIn('block_seq_id', $usedBlockIds)->delete();
                    break;
                case 'custom_field':
                default:
                    // 通常フィールド
                    $values = [
                        'field_id' => $field->id,
                        'value' => $inputVal,
                    ] + $addValues;

                    $attributes = ['field_id' => $values['field_id']];
                    if (!empty($addValues['block_seq_id'])) {
                        $attributes['block_seq_id'] = $addValues['block_seq_id'];
                    }

                    $post->values()->updateOrCreate(
                        $attributes,
                        $values
                    );
                    break;
            }
        }
    }

    protected function saveCategories(Content $post, $categories, Request $request): void
    {
        $companyAndFacility = $this->findCompanyAndFacility($request);
        $company = $companyAndFacility['company'];
        $facility = $companyAndFacility['facility'];

        if ($categories) {
            if (isset($categories[0])) {
                // 複数選択の場合
                $categoryId = [];
                foreach ($categories as $category) {
                    // valueが数値でなければ新規カテゴリとみなす
                    if (isset($category['__isNew__']) && $category['__isNew__']) {
                        // 新規カテゴリ作成
                        $newCategory = $post->categories()->getRelated()->create([
                            'title' => $category['label'],
                            'model_id' => $this->contentModel->id,
                            'company_id' => $company->id,
                            'assignable_type' => get_class($facility),
                            'assignable_id' => $facility->id
                        ]);
                        $categoryId[] = $newCategory->id;
                    } else {
                        $categoryId[] = $category['value'];
                    }
                }
                $post->categories()->sync($categoryId);
            } else {
                // 単一選択の場合
                // valueが数値でなければ新規カテゴリとみなす
                if (isset($categories['__isNew__']) && $categories['__isNew__']) {

                    // 新規カテゴリ作成
                    $newCategory = $post->categories()->getRelated()->create([
                        'title' => $categories['label'],
                        'model_id' => $this->contentModel->id,
                        'company_id' => $company->id,
                        'assignable_type' => get_class($facility),
                        'assignable_id' => $facility->id
                    ]);
                    $categoryId = [$newCategory->id];
                } else {
                    $categoryId = [$categories['value']];
                }
                $post->categories()->sync($categoryId);
            }
        } else {
            // カテゴリ未選択の場合は関連を解除
            $post->categories()->detach();
        }
    }

    protected function validateRequest(Request $request, mixed $post = null): void
    {
        $rules = [];
        $message = [];

        // contentModelのfieldsのうち、is_requiredがtrueのものを必須バリデーション
        $fields = $this->contentModel->fields ?? [];

        $requestData = array_merge($request->request->getIterator()->getArrayCopy(), $request->query->getIterator()->getArrayCopy());

        foreach ($fields as $field) {
            $this->validate->addValidationRules($field, $rules, $message, null, $requestData);
        }

        if (!empty($rules)) {
            Validator::make($requestData, $rules, $message)->validate();
        }
    }

    protected function appendCriteria($criteria = [], $query): void
    {
        parent::appendCriteria($criteria, $query);
    }

    public function findDetail(Request $request, mixed $id, array $with = [], string $flatMethod = 'toFlatArray'): mixed
    {
        // 権限チェックのため、まずオブジェクトとして取得
        $post = $this->model::where(function ($query) use ($request) {
            $criteria = $request->get('criteria', []);
            $this->appendCriteria($criteria, $query);
        })->with($with)->findOrFail($id);

        // created_by / updated_by をレスポンスに含める
        $post->makeVisible(['created_by', 'updated_by']);

        // 権限スコープチェック（スコープでは対応できないため、個別にチェック）
        $this->checkPermissionScope($request, $post, 'read');

        // フラット配列が必要な場合は変換して返す
        return method_exists($post, $flatMethod) && $this->isFlat ? $post->{$flatMethod}() : $post;
    }

    /**
     * 権限スコープをチェック
     */
    protected function checkPermissionScope(Request $request, Content $post, string $permission): void
    {
        $permissionService = app(PermissionService::class);

        $modelName = $request->route('model_name');
        if (!$modelName || !$post->model_id) {
            return;
        }

        $permissionService->checkPermissionScopeForPost(
            $request,
            $post,
            'content_model',
            $post->model_id,
            $permission
        );
    }

    /**
     * 並び替え処理
     * 並び替え権限がある場合は、個別のアイテムに対する権限チェックをスキップ
     */
    public function sort(Request $request): array
    {
        return DB::transaction(function () use ($request) {
            $sortIds = $request->input('sort_ids', []);
            foreach ($sortIds as $key => $id) {
                // 並び替え処理では、findDetailを使わずに直接取得して権限チェックをスキップ
                $post = $this->model::findOrFail($id);
                $post->sort_num = ($key + 1);
                $post->save();
            }
            return ['result' => true];
        });
    }

    /**
     * 削除前処理
     */
    protected function beforeDelete($request, Content $post): void
    {
        // ContentModelを取得（削除時はリレーションから取得）
        if (!$post->relationLoaded('model')) {
            $post->load('model');
        }
        $contentModel = $post->model;
        if ($contentModel) {
            $this->contentModel = $contentModel;
        }

        // 権限スコープチェック
        $this->checkPermissionScope($request, $post, 'delete');

        // WebHook送信（削除前に送信）
        $this->sendWebhook($post, 'deleted');
    }

    /**
     * WebHookを送信
     *
     * @param Content $content
     * @param string $action 'created', 'updated', 'deleted'
     */
    protected function sendWebhook(Content $content, string $action): void
    {
        // ContentModelのwebhook_urlを取得
        $contentModel = $this->contentModel ?? $content->model;
        if (!$contentModel) {
            return;
        }

        $webhookUrl = $contentModel->webhook_url;

        if (empty($webhookUrl)) {
            return;
        }

        try {
            // Contentデータを取得（フロント用の形式）
            $contentData = $content->toFlatFrontArray();

            // 送信データを作成
            $sendData = [
                'action' => $action,
                'timestamp' => now()->timestamp,
                'content' => $contentData,
            ];

            // cURLでPOST送信
            $ch = curl_init();
            curl_setopt_array($ch, [
                CURLOPT_URL => $webhookUrl,
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_POST => true,
                CURLOPT_POSTFIELDS => json_encode($sendData),
                CURLOPT_TIMEOUT => 5,
                CURLOPT_HTTPHEADER => [
                    'Content-Type: application/json',
                    'Accept: application/json',
                ],
                CURLOPT_SSL_VERIFYPEER => false,
            ]);

            curl_exec($ch);
            $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            $error = curl_error($ch);
            curl_close($ch);

            // エラーログ（必要に応じて）
            if ($error || ($httpCode < 200 || $httpCode >= 300)) {
                Log::warning('WebHook送信エラー', [
                    'url' => $webhookUrl,
                    'action' => $action,
                    'content_id' => $content->id,
                    'http_code' => $httpCode,
                    'error' => $error,
                ]);
            }
        } catch (\Exception $e) {
            // エラーが発生しても処理は続行
            Log::error('WebHook送信例外', [
                'url' => $webhookUrl,
                'action' => $action,
                'content_id' => $content->id,
                'error' => $e->getMessage(),
            ]);
        }
    }
}
