<?php

namespace App\Mod\Content\Domain;

use Symfony\Component\HttpFoundation\Request;
use App\Mod\Content\Domain\Models\ContentCategory;
use App\Mod\ContentModel\Domain\Models\ContentModel;

/**
 * @property ContentCategory $model
 * @property ContentModel $contentModel
 */
class ContentCategoryService extends AbstractService
{
    public function __construct(ContentCategory $model)
    {
        parent::__construct($model);
        $this->isCategory = true;
        $this->setContentModel();
    }

    public function findList(Request $request, ?int $limit = null, array $with = [], string $flatMethod = 'toFlatArray'): array
    {
        if (!$limit) {
            $limit = config('content.list.limit');
        }
        return parent::findList($request, $limit, $with, $flatMethod); // TODO: Change the autogenerated stub
    }

    protected function beforeSave($request, $post, &$inputs): void
    {
        $companyAndFacility = $this->findCompanyAndFacility($request);
        $company = $companyAndFacility['company'];
        $facility = $companyAndFacility['facility'];
        $post->company_id = $company->id;
        $post->assignable_type = get_class($facility);
        $post->assignable_id = $facility->id;

        parent::beforeSave($request, $post, $inputs);
    }

    protected function validateRequest(Request $request, mixed $post = null): void
    {
        $request->validate(
            [
                'title' => ['required']
            ],
            [
                'title.required' => 'タイトルは必須項目です。'
            ]
        );
    }
}
