<?php

namespace App\Mod\Content\Domain;

use App\Core\Contract\Domain\Models\ContractCompany;
use App\Core\Contract\Domain\Models\ContractFacility;
use Symfony\Component\HttpFoundation\Request;
use App\Mod\Content\Domain\Models\Content;
use App\Mod\ContentModel\Domain\ContentModelMarkupService;
use App\Mod\ContentModel\Domain\Models\ContentModel;
use App\Mod\ContentModel\Domain\Models\ContentModelMarkup;
use Illuminate\Support\Facades\Blade;
use Illuminate\Support\Facades\Log;

/**
 * FrontContentService
 * フロント用のContentService
 * @property Content $model
 * @property ContentModel $contentModel
 * @property ContentModelMarkupService $contentModelMarkupService
 */
class FrontContentService extends AbstractService
{
    protected $contentModel;
    protected $contentModelMarkupService;

    public function __construct(Content $model, ContentModelMarkupService $contentModelMarkupService)
    {
        parent::__construct($model);
        $this->contentModelMarkupService = $contentModelMarkupService;
        $this->setContentModelFromToken();
    }

    /**
     * リストを取得
     */
    public function findList(Request $request, ?int $limit = null, array $with = [], string $flatMethod = 'toFlatArray'): array
    {
        if (!$limit) {
            $limit = config('content.list.limit');
        }
        return parent::findList($request, $limit, $with, $flatMethod); // TODO: Change the autogenerated stub
    }

    public function findDetail(Request $request, mixed $id, array $with = [], string $flatMethod = 'toFlatArray'): mixed
    {
        $criteria = $request->get('criteria', []);
        $criteria['seq_id'] = $id;
        $request->query->set('criteria', $criteria);
        return parent::findOneBy($request, $with, $flatMethod);
    }

    /**
     * 前の記事と次の記事を取得
     */
    public function findPreviousAndNext(Request $request, int $contentId): array
    {
        return ['previous' => null, 'next' => null];

        // TODO: 実装
        // 現在の記事を取得
        /** @var Content $currentContent */
        $currentContent = $this->model
            ->where('seq_id', $contentId)
            ->where('model_id', $this->contentModel->id)
            ->first();

        if (!$currentContent) {
            return ['previous' => null, 'next' => null];
        }

        // sort + direction を取得（一覧と同じ条件で順位をつける）
        $orderBy = $this->getOrderByFromRequest($request);

        // 並び順を構築
        $orders = [];
        foreach ($orderBy as $col => $dir) {
            $orders[] = [$col, $dir];
        }

        // 同じ model の記事を全件取得（一覧と同じフィルタ条件を適用）
        $criteria = $request->get('criteria', []);
        unset($criteria['seq_id']);
        $query = $this->model->where('model_id', $this->contentModel->id);
        $this->appendCriteria($criteria, $query);
        $this->orderBy($query, $orders);


        // 一覧順を配列で確定
        $all = $query->get(['seq_id']);

        // 現在の位置を特定
        $currentIndex = $all->search(fn($item) => $item->seq_id === $currentContent->seq_id);

        if ($currentIndex === false) {
            return ['previous' => null, 'next' => null];
        }

        // 前後の記事を取得
        $previous = $currentIndex > 0 ? $all[$currentIndex - 1]->toFlatFrontArray() : null;
        $next = $currentIndex < $all->count() - 1 ? $all[$currentIndex + 1]->toFlatFrontArray() : null;

        return [
            'previous' => $previous,
            'next'     => $next,
        ];
    }

    /**
     * 構造化マークアップのリストを取得（ページング）
     */
    public function findMarkupList(Request $request, ?int $limit = null, array $with = [], string $flatMethod = 'toFlatArray'): array
    {
        // 構造化データの取得
        $markup = $this->findMarkup('list');

        // データの取得
        $list = parent::findList($request, $limit, $with, $flatMethod);

        // Bladeを用いて、テンプレートにデータを埋め込む
        $data = ['items' => $list['data'] ?? []];
        $template = $markup->template_json;
        $rendered = Blade::render($template, $data);

        // JSONとしてパース（JSON文字列の場合は配列に変換）
        $decoded = json_decode($rendered, true);

        return ['data' => $decoded];
    }

    /**
     * 構造化マークアップのリストを取得（全件）
     */
    public function findMarkupAll(Request $request, array $with = [], string $flatMethod = 'toFlatArray'): array
    {
        // 構造化データの取得
        $markup = $this->findMarkup('list');

        // データの取得
        $list = parent::findAll($request, $with, $flatMethod);

        // Bladeを用いて、テンプレートにデータを埋め込む
        // テンプレート側でループ処理を行うため、データ全体を渡す
        $template = $markup->template_json;
        $data = ['items' => $list['data'] ?? []];
        $rendered = Blade::render($template, $data);

        // JSONとしてパース（JSON文字列の場合は配列に変換）
        $decoded = json_decode($rendered, true);

        return ['data' => $decoded];
    }

    /**
     * 構造化マークアップの詳細を取得
     */
    public function findMarkupDetail(Request $request, int $id, $with, $flatMethod = 'toFlatArray'): array
    {
        // 構造化データの取得
        $markup = $this->findMarkup('detail');

        // データの取得
        $data = $this->findDetail($request, $id, $with, $flatMethod);

        // Bladeを用いて、テンプレートにデータを埋め込む
        $template = $markup->template_json;
        $rendered = Blade::render($template, $data);

        // JSONとしてパース（JSON文字列の場合は配列に変換）
        $decoded = json_decode($rendered, true);

        return ['data' => $decoded];
    }

    /**
     * 構造化マークアップを取得
     */
    protected function findMarkup(string $markupType): ContentModelMarkup
    {
        return $this->contentModelMarkupService->getModel()->where('model_id', $this->contentModel->id)->where('markup_type', $markupType)->firstOrFail();
    }

    /**
     * 並び順を取得（seq_idが指定されていない場合はdesc）
     */
    protected function getOrderByFromRequest(Request $request): ?array
    {
        $sort = parent::getOrderByFromRequest($request);
        if (!isset($sort['seq_id'])) {
            $sort['seq_id'] = 'asc';
        }

        return $sort;
    }

    /**
     * クエリに条件を追加
     */
    protected function appendCriteria($criteria = [], $query): void
    {
        $this->appendFacilityCriteria($criteria, $query);

        // seq_idでフィルター
        if (isset($criteria['seq_id'])) {
            $query->where('seq_id', $criteria['seq_id']);
        }
        unset($criteria['seq_id']);

        parent::appendCriteria($criteria, $query); // TODO: Change the autogenerated stub
    }
}
