<?php

namespace App\Mod\Content\Domain;

use App\Core\Contract\Domain\Models\ContractCompany;
use App\Mod\Content\Domain\Models\ContentCategory;
use App\Mod\ContentModel\Domain\Models\ContentModel;
use Symfony\Component\HttpFoundation\Request;

/**
 * FrontContentCategoryService
 * フロント用のContentCategoryService
 *
 * @property ContentCategory $model
 * @property ContentModel $contentModel
 */
class FrontContentCategoryService extends AbstractService
{
    protected $contentModel;

    public function __construct(ContentCategory $model)
    {
        parent::__construct($model);
        $this->setContentModelFromToken();
    }

    public function findList(Request $request, ?int $limit = null, array $with = [], string $flatMethod = 'toFlatArray'): array
    {
        if (!$limit) {
            $limit = config('content.list.limit');
        }
        return parent::findList($request, $limit, $with, $flatMethod); // TODO: Change the autogenerated stub
    }

    protected function appendCriteria($criteria = [], $query): void
    {
        $this->appendFacilityCriteria($criteria, $query);
        parent::appendCriteria($criteria, $query); // TODO: Change the autogenerated stub
    }
}
