<?php
namespace App\Core\User\Tests\Unit;

use App\Core\User\Domain\UserService;
use App\Core\User\Domain\Models\User;
use Illuminate\Http\Request;
use Tests\Unit\AbstractUnitTest;

class UserDomainTest extends AbstractUnitTest
{
    /** @var UserService $service */
    protected $service;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->service = \app()->make(UserService::class);
    }

    public function test_list()
    {
        // データ7件作成
        User::factory(7)->create();

        // 1ページ目テスト
        $request = new Request();
        $request->query->add([
            'current' => 1,
            'limit' => 5
        ]);
        $result = $this->service->findList($request);
        $this->assertEquals($result['total'], 7);
        $this->assertEquals(count($result['data']), 5);

        // 2ページ目テスト
        $request = new Request();
        $request->query->add([
            'current' => 2,
            'limit' => 5
        ]);
        $result = $this->service->findList($request);
        $this->assertEquals($result['total'], 7);
        $this->assertEquals(count($result['data']), 2);
    }

    public function test_detail()
    {
        $request = new Request();

        // データ作成
        $createPost = User::factory()->create();
        // データ取得
        $getPost = $this->service->findDetail($request, $createPost->id);
        // 同じデータかテスト
        $this->assertEquals($createPost->title, $getPost->title);
    }

    public function test_save()
    {
        // データ作成テスト
        $inputData = User::factory()->make()->toArray();
        $request = Request::create('/fake-uri', 'POST', $inputData);
        $result = $this->service->save($request);
        $post = User::find($result->id);
        $this->assertEquals($inputData['title'], $post->title);

        // データ更新テスト
        $inputData['title'] .= ' edit';
        $updateRequest = Request::create('/fake-uri/' . $result->id, 'POST', $inputData);
        $this->service->save($updateRequest, $result->id);
        $post = User::find($result->id);
        $this->assertEquals($inputData['title'], $post->title);
    }

    public function test_delete()
    {
        $request = new Request();

        $createPost = User::factory()->create();
        $this->assertEquals(User::count(), 1);

        $this->service->delete($request, $createPost->id);
        $this->assertEquals(User::count(), 0);
    }
}
