<?php
namespace App\Mod\Content\Tests\Unit;

use App\Mod\Content\Domain\ContentService;
use App\Mod\Content\Domain\Models\Content;
use Illuminate\Http\Request;
use Tests\Unit\AbstractUnitTest;

class ContentDomainTest extends AbstractUnitTest
{
    /** @var ContentService $service */
    protected $service;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->service = \app()->make(ContentService::class);
    }

    public function test_list()
    {
        // データ7件作成
        Content::factory(7)->create();

        // 1ページ目テスト
        $request = new Request();
        $request->query->add([
            'current' => 1,
            'limit' => 5
        ]);
        $result = $this->service->findList($request);
        $this->assertEquals($result['total'], 7);
        $this->assertEquals(count($result['data']), 5);

        // 2ページ目テスト
        $request = new Request();
        $request->query->add([
            'current' => 2,
            'limit' => 5
        ]);
        $result = $this->service->findList($request);
        $this->assertEquals($result['total'], 7);
        $this->assertEquals(count($result['data']), 2);
    }

    public function test_detail()
    {
        // データ作成
        $createPost = Content::factory()->create();
        // データ取得
        $getPost = $this->service->findDetail($createPost->id);
        // 同じデータかテスト
        $this->assertEquals($createPost->title, $getPost->title);
    }

    public function test_save()
    {
        // データ作成テスト
        $inputData = Content::factory()->make()->toArray();
        $request = Request::create('/fake-uri', 'POST', $inputData);
        $result = $this->service->save($request);
        $post = Content::find($result->id);
        $this->assertEquals($inputData['title'], $post->title);

        // データ更新テスト
        $inputData['title'] .= ' edit';
        $updateRequest = Request::create('/fake-uri/' . $result->id, 'POST', $inputData);
        $this->service->save($updateRequest, $result->id);
        $post = Content::find($result->id);
        $this->assertEquals($inputData['title'], $post->title);
    }

    public function test_delete()
    {
        $createPost = Content::factory()->create();
        $this->assertEquals(Content::count(), 1);

        $this->service->delete($createPost->id);
        $this->assertEquals(Content::count(), 0);
    }
}
