<?php

namespace App\Core\Contract\Domain;

use App\Domain\BaseService;
use Symfony\Component\HttpFoundation\Request;
use Illuminate\Support\Facades\Validator;
use App\Core\Contract\Domain\Models\ContractCompany;
use App\Domain\AwsService;

/**
 * @property ContractCompany $model
 */
class ContractCompanyService extends BaseService
{

    public function __construct(ContractCompany $model)
    {
        parent::__construct($model);
    }

    public function findList(Request $request, ?int $limit = null, array $with = [], string $flatMethod = 'toFlatArray'): array
    {
        if (!$limit) {
            $limit = config('contract_company.list.limit');
        }
        return parent::findList($request, $limit, $with, $flatMethod); // TODO: Change the autogenerated stub
    }

    public function afterSave(Request $request, mixed $post = null, mixed $id = null): void
    {
        if (config('media_library.storage.disk', 'public') === 's3' && $id === null) {
            // AWSバケットの生成
            $awsService = AwsService::getInstance();
            $awsService->generateBucket($post->alias);
        }
    }

    public function beforeDelete(Request $request, mixed $post = null): void
    {
        if (config('media_library.storage.disk', 'public') === 's3') {
            // AWSバケットの削除
            $awsService = AwsService::getInstance();
            $awsService->deleteBucket($post->alias);
        }
    }

    public function appendCriteria(?array $criteria = [], $query): void
    {
        parent::appendCriteria($criteria, $query); // TODO: Change the autogenerated stub
    }

    public function validateRequest(Request $request, mixed $post = null): void
    {
        // 必要に応じてコメントアウト外し、バリデーションを追加する
        $validator = Validator::make(
            $request->all(),
            [
                "company_name" => ['required'],
                "alias" => ['required', 'unique:contract_company,alias,' . $post->id],
            ],
            [
                'company_name.required' => '企業名は必須項目です。',
                'alias.required' => 'エイリアスは必須項目です。',
                'alias.unique' => 'このエイリアスは既に使用されています。',
            ]
        );

        $validator->validate();
    }
}
